[layout]
sidebar = false
emoji = false

[listings]
pageHeader = 'title'

[directoryUI.search]
placeholder = "Search across {0} guides"
showCount = true
icon = "tabler:search"

[directoryUI.search.tags]
display = "show-all"
intersection = false

[directoryUI.grid]
list = false
type = "small-card-grid"

[directoryUI.grid.emptyState]
text = "Nothing matched this filter yet."
type = "button"                                              # options: button, simple, link
icon = "tabler:exclamation-mark"

[directoryUI.grid.card]
image = false

[directoryUI.grid.submit]
show = false
first = false
title = "Suggest a page"
description = "Share a page idea once the editorial pipeline is ready."
hideable = true

[directoryUI.featured]
showOnAllPages = true
showOnSide = true
icon = "tabler:star"
labelForCard = "Featured"

[ui.icons]
dark = "tabler:moon"
light = "tabler:sun"
youtube = "tabler:brand-youtube"
x = "tabler:brand-twitter"
instagram = "tabler:brand-instagram"
facebook = "tabler:brand-facebook"
github = "tabler:brand-github"
